### PR TITLE
Statically-defined responsive images

### PR DESCRIPTION
**Pull request by kellysutton**
**Alternate Title:** Boiling the Ocean with Markup

**Note:** Before diving in here, read ["srcset and sizes"](https://ericportis.com/posts/2014/srcset-sizes/) by Eric Portis.

**Note:** This only covers the resolution-switching responsive image use case, but can also be applied to the art direction use case.

Responsive images are difficult to implement correctly. I believe the agreed upon nomenclature is ["terrible"](https://ericportis.com/posts/2014/srcset-sizes/):

    Media-query-based responsive image source-picking is terrible because while most responsive designers have settled on varying a page’s layout based on one variable (viewport width), when dealing with responsive images, we’re really concerned with three variables:

      - The rendered size (in CSS pixels) of the image on our layout
      - The screen density
      - The dimensions of the variously-sized files at our disposal

Using a solution like imgix eliminates the last concern in that list: we
can generate derivative images from a single master at arbitrary dimensions
on-the-fly.

To achieve performant responsive imagery, we must declare each image size
within the markup. By doing this, we do not require JavaScript to execute before
displaying images.

## Pixel Perfection

A quick note about pixel perfection. This approach assumes that the implementing
designer or front-end engineer care about pixel perfection. We think more
people should care about pixel perfection. Your image has already been resized
once on the server when creating `person-small.jpg`. If the image is not the
exact perfect size, the client must do some amount of interpolation on the
image to get the pixels delivered to map to the pixles on the screen. Sharp
lines become blurry, and detail is lost. (For more on the
performance implications of doing client-side resizes, check out [this talk by
Tim Kadlec](https://www.youtube.com/watch?v=jP68rCjSSjM).)

Each successive resize and compression slowly kills image quality. By actively
working to reduce the number of times images are resized, whether on the client
or server, we ensure that images are served at the highest quality.

## A Sea of Markup

To sidestep the requirement of JavaScript for delivering pixel-perfect image
experiences, all of the imperative computation done to request a new size
of the image must now be _declared_ in the markup. To do this, we reach for
the `srcset` attribute on the `` and we put it through its paces:
We declare a new image for just about every possible size we think we'll need.

The result looks something like this:

```html
<img srcset="https://assets.imgix.net/flower.jpg?w=50 50w,
             https://assets.imgix.net/flower.jpg?w=100 100w,
             https://assets.imgix.net/flower.jpg?w=150 150w,
             ...
             https://assets.imgix.net/flower.jpg?w=5200 5200w,
             https://assets.imgix.net/flower.jpg?w=5260 5260w"
     src="https://assets.imgix.net/flower.jpg?w=800"
     alt="A white flower"
/>
```

In the biggest case, this results in over 100 `srcset` rules! This
can make a single image tag weigh more than 8 KB in HTML. To anyone keeping
an eye on payload sizes, that sounds like an intractable proposition.

But there are a few wrinkles here that make this not as insane as it
might seem.

0. **This content compresses exremely well.** The above example gzips down to 736 bytes. The amount of data that needs to be sent over the wire to convey a very large set of possibilities is very small.
0. **Browsers are very good at parsing markup.** Keep in mind this is markup, not JavaScript. The browser will have parsed this and preflighted the image it needs _before_ it even begins executing the JavaScript. Although the amount of markup seems explosive, it still delivers a better experience than the JavaScript alternative.
0. **This allow the browser to request only the amount of pixels it needs.** This can help make up for the dirty feeling that we've got lots of markup, because we can guarantee that fewer image bytes get sent on the wire.

## Wrangling with `sizes`

There is a bit of information that we can use to whittle down the number
of `srcset` rules we define, and that is the `sizes` attribute. The `sizes`
attribute tells the image how to behave at different viewport widths. For our purposes,
it also defines the bounds of what we need to generate.

When not specified, `sizes` is interpreted as `100vw` or "100% of the viewport width."

Case and point: if we set `sizes` to `"(min-width: 800px) 800w, 100vw"` we can prune
the `srcset` rule we generate. This `sizes` example says "When the viewport is 800px
or wider, just use the image that is defined by `800w`. Otherwise, fall back to 100%
of the viewport width." From this we can infer that we will _never need an image
wider than 800w and can remove those from our `srcset` rules_. Boom, savings.

## Better targeting `srcset` rules

Rather than just iterate through a bunch of pixel widths, it's better if we keep in
mind how responsive images are implemented in practice. There's one pattern in
particular that's important to pay attention to: more often than not, mobile devices use
full-bleed (or `100vw`) images. We should define rules that exactly target these devices
to provide for a pixel-perfect experience.

As such, this PR adds in a few rules for common device widths and DPRs like iPhone, iPads,
and their Android counterparts.

## The Result

The resulting API is something that is simple and expressive:

```erb
<%= ix_responsive_image_tag('/flower.jpg', { sizes: "(min-width: 800px) 800w, 100vw" }) %>
```

That will generate the following HTML:

```html
<img srcset="https://assets.imgix.net/flower.jpg?w=50 50w,
             https://assets.imgix.net/flower.jpg?w=100 100w,
             https://assets.imgix.net/flower.jpg?w=150 150w,
             ...
             https://assets.imgix.net/flower.jpg?w=5200 800w"
     sizes="(min-width: 800px) 800w, 100vw"
     src="https://assets.imgix.net/flower.jpg?w=800"
     alt="A white flower"
/>
```

This markup is no bigger than it needs to be to deliver a statically-defined,
fully-responsive experience that provides pixel-pefect images to all mobile
devices currently in existence. It compresses well, since much of the information
is repeated.

### CODE REVIEW

**Comment by kellysutton** [comment]
Doing a little bit of testing here to see how much this approach adds to the page's HTML weight. Generating an image at a step of every 100 pixels, We get the following on an iPhone 6:

| Mode | Page Weight | Image Weight | Image Widths off by...
-------------------------------------------
| Original | 50.91 KB | 253 KB | 50px |
| With `big-srcset` | 74.96 KB |  440 KB | 0px |

**Comment by nhoizey** [comment]
Interesting!

I didn't even know we can use `w` in the `sizes` values…

**Comment by paulstraw** [comment]
@nhoizey Yup! It's a great tool, especially for this case because of how imgix works. Eric Portis has an incredible overview of this stuff that I always recommend: https://ericportis.com/posts/2014/srcset-sizes/. ^_^

**Comment by paulstraw** [comment]
Going to switch this to let users specify the max physical pixel width they want generated instead of manually regexing the `sizes` attribute. The `sizes` parsing would only work if specified using `min-width` rules, and doesn't necessarily account for different DPR devices. @kellysutton, work for you?

**Comment by paulstraw** [comment]
Other than that, this should be good to go after I write up some docs/examples.

**Comment by kellysutton** [comment]
Yeah, that works. The `sizes` implementation was incomplete. Let's land this with the config-based approach (with a sensible default), and then see if we can't introduce the `sizes` parsing on another pass.

**Pull request merged**
